include: _hellaswag_template.yaml
task: hellaswag_rc
output_type: multiple_choice
test_split: validation
process_docs: !function utils.process_hellaswag_docs
doc_to_text: "{{activity_label}}: {{ctx_a}} {{ctx_b}}"
doc_to_target: "{{label | int}}"
doc_to_choice: "{{endings}}"
fewshot_config:
  sampler: first_n
  samples: !function utils.get_hellaswag_olmes_rc_fewshot
metric_list:
  - metric: acc
    aggregation: mean
    higher_is_better: true
  - metric: acc_norm # acc_norm in lm-eval-harness IS acc_per_char in OLMES
    aggregation: mean
    higher_is_better: true
metadata:
  version: 1.0
  description: "HellaSwag - commonsense inference"
  fewshot_source: "OLMES:hellaswag"
