# SocialIQA German Multiple Choice Template
dataset_path: ellamind/siqa-multilingual
dataset_name: deu
validation_split: validation
fewshot_config:
  sampler: first_n
  samples: !function utils.list_fewshot_samples
num_fewshot: 5
output_type: multiple_choice
doc_to_text: "Frage: {{context}} {{question}}\n{% for i in range(choices|length) %} {{'ABCDEFGHIJ'[i]}}. {{choices[i]}}\n{% endfor %}Antwort:"
doc_to_target: "{{answer_idx}}"
doc_to_choice: "{{'ABCDEFGHIJ'[:choices|length] | list}}"
metric_list:
  - metric: acc
    aggregation: mean
    higher_is_better: true
  - metric: acc_norm
    aggregation: mean
    higher_is_better: true
metadata:
  version: 1.0
