include: _agieval_mc_template.yaml
task: deu_agieval_sat_math_mc
num_fewshot: 5
process_docs: !function utils.filter_sat_math
fewshot_config:
  sampler: first_n
  samples: !function utils.list_fewshot_sat_math
metadata:
  version: 1.0
  description: "AGIEval SAT Math German - Multiple Choice"
