include: _agieval_mc_template.yaml
task: deu_agieval_sat_en_without_passage_mc
process_docs: !function utils.filter_sat_en_without_passage
fewshot_config:
  sampler: first_n
  samples: !function utils.list_fewshot_sat_en_without_passage
metadata:
  version: 1.0
  description: "AGIEval SAT English (no passage) German - Multiple Choice"
