include: _agieval_mc_template.yaml
task: deu_agieval_gaokao_english_mc
process_docs: !function utils.filter_gaokao_english
fewshot_config:
  sampler: first_n
  samples: !function utils.list_fewshot_gaokao_english
metadata:
  version: 1.0
  description: "AGIEval Gaokao English German - Multiple Choice"
