include: _agieval_bpb_template.yaml
task: deu_agieval_lsat_lr_bpb
process_docs: !function utils.filter_lsat_lr
fewshot_config:
  sampler: first_n
  samples: !function utils.list_fewshot_lsat_lr
metadata:
  version: 1.0
  description: "AGIEval LSAT Logical Reasoning German - Bits Per Byte"
