include: _agieval_mc_template.yaml
task: deu_agieval_lsat_rc_mc
process_docs: !function utils.filter_lsat_rc
fewshot_config:
  sampler: first_n
  samples: !function utils.list_fewshot_lsat_rc
metadata:
  version: 1.0
  description: "AGIEval LSAT Reading Comprehension German - Multiple Choice"
