include: _default_mc_template.yaml
task: deu_glp_perfect_aux_mc
process_docs: !function utils.filter_perfect_aux
metadata:
  version: 1.0
  description: "German perfect auxiliary/participle errors (MC)"
