include: _default_rc_template.yaml
task: deu_glp_word_order_nebensatz_rc
process_docs: !function utils.filter_word_order_nebensatz
metadata:
  version: 1.0
  description: "German subordinate clause word order errors"
