include: _default_mc_template.yaml
task: deu_glp_adjective_ending_mc
process_docs: !function utils.filter_adjective_ending
metadata:
  version: 1.0
  description: "German adjective ending errors (MC)"
