include: _mbpp_template.yaml
task: deu_mbpp_bpb
output_type: loglikelihood
target_delimiter: ""
process_docs: !function utils.strip_cr
doc_to_text: !function utils.doc_to_text_bpb
doc_to_target: !function utils.doc_to_target_bpb
num_fewshot: 3
fewshot_config:
  sampler: first_n
  samples: !function utils.get_mbpp_fewshot
process_results: !function utils.process_results_bpb
metric_list:
  - metric: bits_per_byte
    aggregation: mean
    higher_is_better: false
metadata:
  version: 1.0
  description: "MBPP German - BPB evaluation"
