include: _drop_rc_template.yaml
task: drop_rc
dataset_path: allenai/drop-gen2mc
output_type: multiple_choice
doc_to_text: "Passage: {{passage_original | trim}}\nQuestion: {{question_original}}\nAnswer:"
doc_to_target: "{{ ['A', 'B', 'C', 'D', 'E'].index(answerKey) }}"
doc_to_choice: "{{choices.text}}"
fewshot_config:
  sampler: first_n
  samples: !function utils.get_drop_rc_fewshot
metric_list:
  - metric: acc
    aggregation: mean
    higher_is_better: true
  - metric: acc_norm
    aggregation: mean
    higher_is_better: true
metadata:
  version: 1.0
  description: "DROP - discrete reasoning over paragraphs (gen2mc multiple choice)"
  fewshot_source: "OLMES:drop_mc"
