include: _lambada_template.yaml
task: lambada_gen
output_type: generate_until
doc_to_text: "{{text.rsplit(' ', 1)[0]}}"
doc_to_target: "{{' ' + text.rsplit(' ', 1)[1]}}"
generation_kwargs:
  max_gen_toks: 5
  until:
    - "\n"
    - "."
    - ","
  do_sample: false
  temperature: 0.0
process_results: !function utils.process_results_lambada
metric_list:
  - metric: acc
    aggregation: mean
    higher_is_better: true
metadata:
  version: 1.0
  description: "LAMBADA word prediction"
