# Italian AGIEval — Rank Classification (8 subsets)
group: ita_agieval_rc
task:
  - ita_agieval_aqua_rat_rc
  - ita_agieval_gaokao_english_rc
  - ita_agieval_logiqa_en_rc
  - ita_agieval_lsat_ar_rc
  - ita_agieval_lsat_lr_rc
  - ita_agieval_lsat_rc_rc
  - ita_agieval_sat_en_rc
  - ita_agieval_sat_math_rc
aggregate_metric_list:
  - metric: acc
    aggregation: mean
    weight_by_size: false
  - metric: acc_norm
    aggregation: mean
    weight_by_size: false
metadata:
  version: 1.0
  description: "Italian AGIEval — Rank Classification"
