# Italian AGIEval — Multiple Choice (8 subsets)
group: ita_agieval_mc
task:
  - ita_agieval_aqua_rat_mc
  - ita_agieval_gaokao_english_mc
  - ita_agieval_logiqa_en_mc
  - ita_agieval_lsat_ar_mc
  - ita_agieval_lsat_lr_mc
  - ita_agieval_lsat_rc_mc
  - ita_agieval_sat_en_mc
  - ita_agieval_sat_math_mc
aggregate_metric_list:
  - metric: acc
    aggregation: mean
    weight_by_size: false
  - metric: acc_norm
    aggregation: mean
    weight_by_size: false
metadata:
  version: 1.0
  description: "Italian AGIEval — Multiple Choice"
