include: _arc_rc_template.yaml
task: arc_easy_rc
dataset_name: ARC-Easy
fewshot_config:
  sampler: first_n
  samples: !function utils.get_arc_easy_fewshot
metadata:
  version: 1.0
  description: "ARC Easy reading comprehension"
  fewshot_source: "OLMES:ARC-Easy"
