include: _naturalqs_template.yaml
task: naturalqs_rc
dataset_path: allenai/nq-gen2mc
output_type: multiple_choice
doc_to_text: "Question: {{question}}\nAnswer:"
doc_to_target: "{{ ['A', 'B', 'C', 'D', 'E'].index(answerKey) }}"
doc_to_choice: "{{choices.text}}"
fewshot_config:
  sampler: first_n
  samples: !function utils.get_naturalqs_rc_fewshot
metric_list:
  - metric: acc
    aggregation: mean
    higher_is_better: true
  - metric: acc_norm
    aggregation: mean
    higher_is_better: true
metadata:
  version: 1.0
  description: "Natural Questions - open domain QA (gen2mc multiple choice)"
  fewshot_source: "OLMES:naturalqs_mc"
