# Italian Non-STEM Multiple Choice Tasks
group: ita_nonstem_qa_mc
task:
  - ita_mmmlu_filtered_nonstem_mc
aggregate_metric_list:
  - metric: acc
    aggregation: mean
    weight_by_size: false
  - metric: acc_norm
    aggregation: mean
    weight_by_size: false
metadata:
  version: 1.0
  description: "Italian non-STEM multiple choice QA tasks"
