group: fra_gpqa_mc
task:
  - fra_gpqa_main_mc
  - fra_gpqa_diamond_mc
aggregate_metric_list:
  - metric: acc
    aggregation: mean
    weight_by_size: false
  - metric: acc_norm
    aggregation: mean
    weight_by_size: false
metadata:
  version: 1.0
  description: "GPQA French MC tasks (main + diamond)"
