include: _medmcqa_template.yaml
task: medmcqa_mc
output_type: multiple_choice
doc_to_text: "Question: {{question}}\n A. {{opa}}\n B. {{opb}}\n C. {{opc}}\n D. {{opd}}\nAnswer:"
doc_to_target: "{{cop}}"
doc_to_choice: ["A", "B", "C", "D"]
fewshot_split: train
metric_list:
  - metric: acc
    aggregation: mean
    higher_is_better: true
  - metric: acc_norm # IS acc_per_char in OLMES
    aggregation: mean
    higher_is_better: true
metadata:
  version: 1.0
  description: "MedMCQA medical multiple choice"
