include: _medmcqa_template.yaml
task: medmcqa_bpb
output_type: loglikelihood
doc_to_text: "Question: {{question}}\nAnswer:"
target_delimiter: ""
doc_to_target: " {{[opa, opb, opc, opd][cop]}}"
process_results: !function utils.process_results_bpb
metric_list:
  - metric: bits_per_byte
    aggregation: mean
    higher_is_better: false
metadata:
  version: 1.0
  description: "MedMCQA - BPB evaluation"
