include: _agieval_rc_template.yaml
task: agieval_logiqa_en_rc
dataset_path: hails/agieval-logiqa-en
fewshot_config:
  sampler: first_n
  samples: !function utils.list_fewshot_logiqa_en
metadata:
  version: 1.0
  description: "AGIEval LogiQA - Rank Classification"
