include: _agieval_bpb_template.yaml
task: agieval_lsat_ar_bpb
dataset_path: hails/agieval-lsat-ar
fewshot_config:
  sampler: first_n
  samples: !function utils.list_fewshot_lsat_ar
metadata:
  version: 1.0
  description: "AGIEval LSAT Analytical Reasoning - Bits Per Byte"
