include: _agieval_rc_template.yaml
task: agieval_sat_math_rc
dataset_path: hails/agieval-sat-math
num_fewshot: 5
fewshot_config:
  sampler: first_n
  samples: !function utils.list_fewshot_sat_math
metadata:
  version: 1.0
  description: "AGIEval SAT Math - Rank Classification"
