include: _agieval_rc_template.yaml
task: agieval_lsat_rc_rc
dataset_path: hails/agieval-lsat-rc
fewshot_config:
  sampler: first_n
  samples: !function utils.list_fewshot_lsat_rc
metadata:
  version: 1.0
  description: "AGIEval LSAT Reading Comprehension - Rank Classification"
